name: Clang Format Check

on: [push, pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install clang-format
    - name: Install clang-format
      run: sudo apt-get install -y clang-format

    # Step 3: Run clang-format in check mode
    - name: Run clang-format
      run: |
      for FILE in **/*.cpp; do
      	  TEMP_FILE=$(mktemp)

    	  clang-format --style=Google "$FILE" > "$TEMP_FILE"

    	  if ! diff -q "$FILE" "$TEMP_FILE" >/dev/null 2>&1; then
	  exit 1 
          fi

          rm "$TEMP_FILE"
      done

      for FILE in **/*.h; do
      	  TEMP_FILE=$(mktemp)

      	  clang-format --style=Google "$FILE" > "$TEMP_FILE"

    	  if ! diff -q "$FILE" "$TEMP_FILE" >/dev/null 2>&1; then
	  exit 1
          fi

    	  rm "$TEMP_FILE"
      done
